### ISSUE TITLE
ClassCastException in MailService with Spring CGLIB Proxies

### ISSUE THREAD

**Issue by hide212131** [jhipster/generator-jhipster-native#101]
Related to https://github.com/jhipster/generator-jhipster-native/pull/100#issuecomment-1826735027

Startup fails due to the following error:

> ```
> [0] Caused by: java.lang.ClassCastException: org.springframework.aop.framework.CglibAopProxy$SerializableNoOp cannot be cast to org.springframework.cglib.proxy.Dispatcher
> [0] 	at com.mycompany.myapp.service.MailService$$SpringCGLIB$$0.setCallbacks(<generated>)
> [0] 	at org.springframework.aop.framework.ObjenesisCglibAopProxy.createProxyClassAndInstance(ObjenesisCglibAopProxy.java:91)
> [0] 	at org.springframework.aop.framework.CglibAopProxy.buildProxy(CglibAopProxy.java:213)
> ```

**Comment by hide212131** [comment]
@mshima With the fix for https://github.com/jhipster/generator-jhipster/pull/24431/ , it started successfully and all e2e tests passed.
